/*
 * @Author: simon
 * @Description: 
 * @LastEditors: simon
 */
export const mutationsTypes = {
  'SET_CONFIG': 'SET_CONFIG',
  'SET_IM_Info': 'SET_IM_Info',
  'SET_IM_LAST_NOTICE': 'SET_IM_LAST_NOTICE',
  'SET_IM_USER_KICK': 'SET_IM_USER_KICK',
  'SET_UP_IM_USER': 'SET_UP_IM_USER',
  'SET_FIRST_PROFILE_SYNC': 'SET_FIRST_PROFILE_SYNC',
  'SET_IM_LOGIN_STATE': 'SET_IM_LOGIN_STATE',
  'SET_CONVERSATION_LIST': 'SET_CONVERSATION_LIST',
}

export const actionsTypes = {
  'GET_CONFIG': 'GET_CONFIG',
  'ENSURE_IM_LOGIN': 'ENSURE_IM_LOGIN',
  'INIT_FLOOIM': 'INIT_FLOOIM', //初始化im
  'SET_IM_LOGIN': 'SET_IM_LOGIN', // im登录
  'WAIT_IM_READY_LOGIN': 'WAIT_IM_READY_LOGIN', // 检查im状态
  'SET_IM_OUT': 'SET_IM_OUT', // im退出
  'ADD_IM_LISTENERS': 'ADD_IM_LISTENERS', // 监听im的回调
  'REMOVE_IM_LISTENERS': 'REMOVE_IM_LISTENERS', // 移除监听
  'SYNC_USER_INFO': 'SYNC_USER_INFO', // 同步当前用户信息到 IM
  'UPDATE_USER_IM_INFO': 'UPDATE_USER_IM_INFO', // 更新
  'SEND_GROUP_MESSAGE': 'SEND_GROUP_MESSAGE', // 发送 group 消息
  'SEND_ROSTER_MESSAGE': 'SEND_ROSTER_MESSAGE', // 发送 roster (私聊) 消息
  'MESSAGE_SEND_STATE_CHANGE': 'MESSAGE_SEND_STATE_CHANGE', // 发送 group 消息
  'RECEIVE_GROUP_MSG': 'RECEIVE_GROUP_MSG', // 收到 group 消息
  'RECEIVE_ROSTER_MSG': 'RECEIVE_ROSTER_MSG', // 收到 roster 消息
  'RECEIVE_IM_MSG': 'RECEIVE_IM_MSG', // 收到 IM 消息 (统一处理)
  "CLEAR_LOGIN_INFO": 'CLEAR_LOGIN_INFO', // 登出

  "REFRESH_ROSTERS_INFO": 'REFRESH_ROSTERS_INFO', // 重新获取 rosters 的信息。

  'REFRESH_IM_LOGIN_STATE': 'REFRESH_IM_LOGIN_STATE',

  'REFRESH_CONVERSATION_LIST': 'REFRESH_CONVERSATION_LIST', // 刷新会话列表
}